
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: insurance
spec:
  replicas: 1
  selector:
    matchLabels:
      app: insurance
  template:
    metadata:
      labels:
        app: insurance
    spec:
      containers:
        - name: insurance
          image: snehaldhul/insurance-image:latest
          ports:
            - containerPort: 8081
          env:
            - name: PORT
              value: "8081"
---
apiVersion: v1
kind: Service
metadata:
  name: insurance
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    app: insurance
